# Generated by Django 5.2.9 on 2026-01-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='guidance_message',
            field=models.TextField(blank=True),
        ),
    ]
