# Generated by Django 5.2.9 on 2026-01-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('general', 'General'), ('stress', 'Stress'), ('anxiety', 'Anxiety'), ('sleep', 'Sleep'), ('depression', 'Depression'), ('exam', 'Exam Stress')], max_length=20)),
                ('severity', models.CharField(choices=[('all', 'All'), ('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='all', max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
    ]
