# Generated by Django 5.2.9 on 2026-01-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_communitylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(default='guide', max_length=20),
        ),
    ]
